### PR TITLE
CGXDateTime fixes and improvements.

### PR DESCRIPTION
**Pull request by gvtret**
1. Use localtime_r() instead of localtime(). Fix multi threaded issues.
2. Add comparison operators.

### CODE REVIEW

**Comment by gurux-kurumi** [comment]
This can't be accepted because all compilers don't support localtime_r. Operators don't check the deviation.

**Comment by gvtret** [comment]
> This can't be accepted because all compilers don't support localtime_r. Operators don't check the deviation.

from manpages: "The thread-safe versions, asctime_r(), ctime_r(), gmtime_r(), and localtime_r(), are specified by SUSv2."
So first of all this specification was issued in 1997.
Second, it is linux OS function. Only from C23 it shall become function in C language standard. Work was tested with gcc 4.9.2

**Comment by gvtret** [comment]
> .... Operators don't check the deviation.

As wel as CGXDateTime::CompareTo(CGXDateTime& antherDate) don't check deviation too.

**Comment by gurux-kurumi** [comment]
Hi,

This is used with systems that don't use Linux. Actually, there is no operating system at all. 
It's possible to add a compiler flag and check if you are using Linux, but it doesn't work as you proposed. 
In general, don't use this from multiple threads. It might cause problems.

You are right on CGXDateTime::CompareTo and I created an issue from it. 

BR,
Mikko

**Pull request closed without merging**
